apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ghas-experiment-1
  annotations:
    github.com/project-slug: marcos-free-sandbox/ghas-experiment-1
spec:
  type: other
  lifecycle: unknown
  owner: guests
